[default_config]
version = "0.10.0"
assembler = "nasm"
instruction_set = "x86"

[default_config.opts]
compiler = "i686-unknown-elf-gcc"
compile_flags_txt = [
    "cc",
    "-std=c11",
    "-x",
    "assembler-with-cpp",
    "-target",
    "i686-unknown-elf",
    "-nostdinc",
    "-nostdlib",
    "-ffreestanding",
    "-fno-builtin",
]
diagnostics = true
default_diagnostics = false
